micronaut:
  application:
    name: cqrs-framework

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: false
    failOnUnknownProperties: false

cqrs:
  scheduler:
    prefix: 'cqrs'
    poolSize: 4

